# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FetalMRI_Window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 833)
        MainWindow.setStyleSheet("background-color:rgb(4, 51, 57)")
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.CentralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainWidget = QtWidgets.QWidget(self.CentralWidget)
        self.mainWidget.setStyleSheet("background-color: rgb(4, 51, 57);")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.mainWidget)
        self.label.setStyleSheet("background-color: rgba(4, 51, 57, 20)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../.designer/backup/images/brain_large.jpg"))
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.mainWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../../.designer/backup/images/casmip.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.title = QtWidgets.QLabel(self.mainWidget)
        self.title.setStyleSheet("font: italic 30pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.load_nii_btn = QtWidgets.QPushButton(self.mainWidget)
        self.load_nii_btn.setStyleSheet("font: 75 13pt\"Nirmala UI Semilight\";\n"
"color: rgb(207, 241, 242);\n"
"background-color: rgb(102, 132, 140);\n"
"border-color: rgb(209, 238, 242);")
        self.load_nii_btn.setObjectName("load_nii_btn")
        self.verticalLayout_3.addWidget(self.load_nii_btn)
        self.load_dir_btn = QtWidgets.QPushButton(self.mainWidget)
        self.load_dir_btn.setStyleSheet("font: 75 13pt\"Nirmala UI Semilight\";\n"
"color: rgb(207, 241, 242);\n"
"background-color: rgb(102, 132, 140);\n"
"border-color: rgb(209, 238, 242);")
        self.load_dir_btn.setObjectName("load_dir_btn")
        self.verticalLayout_3.addWidget(self.load_dir_btn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.mainWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1218, 47))
        self.menubar.setStyleSheet("background-color:rgb(195, 223, 226)")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("background-color:rgb(195, 223, 226)")
        self.menuFile.setObjectName("menuFile")
        self.menuWorkspace = QtWidgets.QMenu(self.menubar)
        self.menuWorkspace.setStyleSheet("background-color:rgb(195, 223, 226)")
        self.menuWorkspace.setObjectName("menuWorkspace")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionOpen_Nifti_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_Nifti_File.setObjectName("actionOpen_Nifti_File")
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionSave_Segmentation.setEnabled(False)
        self.actionSave_Segmentation.setObjectName("actionSave_Segmentation")
        self.actionOpen_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionOpen_Segmentation.setEnabled(False)
        self.actionOpen_Segmentation.setObjectName("actionOpen_Segmentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave_Points = QtWidgets.QAction(MainWindow)
        self.actionSave_Points.setEnabled(False)
        self.actionSave_Points.setObjectName("actionSave_Points")
        self.actionLoad_Points = QtWidgets.QAction(MainWindow)
        self.actionLoad_Points.setEnabled(False)
        self.actionLoad_Points.setObjectName("actionLoad_Points")
        self.actionProcess_Ready_Files = QtWidgets.QAction(MainWindow)
        self.actionProcess_Ready_Files.setObjectName("actionProcess_Ready_Files")
        self.actionStandard_View = QtWidgets.QAction(MainWindow)
        self.actionStandard_View.setObjectName("actionStandard_View")
        self.actionContrast_View = QtWidgets.QAction(MainWindow)
        self.actionContrast_View.setEnabled(False)
        self.actionContrast_View.setObjectName("actionContrast_View")
        self.actionMarked_Files = QtWidgets.QAction(MainWindow)
        self.actionMarked_Files.setObjectName("actionMarked_Files")
        self.actionShow_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionShow_Segmentation.setCheckable(True)
        self.actionShow_Segmentation.setChecked(True)
        self.actionShow_Segmentation.setEnabled(False)
        self.actionShow_Segmentation.setObjectName("actionShow_Segmentation")
        self.actionSave_All_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionSave_All_Segmentation.setEnabled(False)
        self.actionSave_All_Segmentation.setObjectName("actionSave_All_Segmentation")
        self.actionRun_All_Workspace = QtWidgets.QAction(MainWindow)
        self.actionRun_All_Workspace.setEnabled(False)
        self.actionRun_All_Workspace.setObjectName("actionRun_All_Workspace")
        self.actionShow_Scan = QtWidgets.QAction(MainWindow)
        self.actionShow_Scan.setCheckable(True)
        self.actionShow_Scan.setChecked(True)
        self.actionShow_Scan.setObjectName("actionShow_Scan")
        self.actionSave_current_scan_ROI = QtWidgets.QAction(MainWindow)
        self.actionSave_current_scan_ROI.setObjectName("actionSave_current_scan_ROI")
        self.actionSave_all_scans_ROI = QtWidgets.QAction(MainWindow)
        self.actionSave_all_scans_ROI.setObjectName("actionSave_all_scans_ROI")
        self.menuFile.addAction(self.actionOpen_Nifti_File)
        self.menuFile.addAction(self.actionOpen_Directory)
        self.menuFile.addAction(self.actionExit)
        self.menuWorkspace.addAction(self.actionSave_Segmentation)
        self.menuWorkspace.addAction(self.actionOpen_Segmentation)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.actionSave_Points)
        self.menuWorkspace.addAction(self.actionLoad_Points)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.actionSave_All_Segmentation)
        self.menuWorkspace.addAction(self.actionRun_All_Workspace)
        self.menuView.addAction(self.actionShow_Segmentation)
        self.menuView.addAction(self.actionShow_Scan)
        self.menuTools.addAction(self.actionProcess_Ready_Files)
        self.menuTools.addAction(self.actionMarked_Files)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSave_current_scan_ROI)
        self.menuTools.addAction(self.actionSave_all_scans_ROI)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWorkspace.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Fetal MRI Seg Tool"))
        self.load_nii_btn.setText(_translate("MainWindow", "Load Nifti File"))
        self.load_dir_btn.setText(_translate("MainWindow", "Load Dicom Directory"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuWorkspace.setTitle(_translate("MainWindow", "Workspace"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionOpen_Nifti_File.setText(_translate("MainWindow", "Open Nifti File"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_Segmentation.setText(_translate("MainWindow", "Save Segmentation"))
        self.actionSave_Segmentation.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_Segmentation.setText(_translate("MainWindow", "Open Segmentation"))
        self.actionOpen_Segmentation.setShortcut(_translate("MainWindow", "Ctrl+Shift+W"))
        self.actionAbout.setText(_translate("MainWindow", "About SegTool"))
        self.actionSave_Points.setText(_translate("MainWindow", "Save Points"))
        self.actionSave_Points.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionLoad_Points.setText(_translate("MainWindow", "Load Points"))
        self.actionProcess_Ready_Files.setText(_translate("MainWindow", "Process Ready Files"))
        self.actionProcess_Ready_Files.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Load and perform segmentation on directory containing Nifti files that have been preprocessed (marked with borders).</p></body></html>"))
        self.actionStandard_View.setText(_translate("MainWindow", "Standard View"))
        self.actionContrast_View.setText(_translate("MainWindow", "Contrast View"))
        self.actionContrast_View.setWhatsThis(_translate("MainWindow", "Improve contrast of image"))
        self.actionMarked_Files.setText(_translate("MainWindow", "Marked Files"))
        self.actionShow_Segmentation.setText(_translate("MainWindow", "Show Segmentation"))
        self.actionShow_Segmentation.setShortcut(_translate("MainWindow", "S"))
        self.actionSave_All_Segmentation.setText(_translate("MainWindow", "Save All Segmentation"))
        self.actionRun_All_Workspace.setText(_translate("MainWindow", "Run All Workspace"))
        self.actionShow_Scan.setText(_translate("MainWindow", "Show Scan"))
        self.actionShow_Scan.setShortcut(_translate("MainWindow", "I"))
        self.actionSave_current_scan_ROI.setText(_translate("MainWindow", "Save current scan ROI"))
        self.actionSave_all_scans_ROI.setText(_translate("MainWindow", "Save all scans ROI"))

